# ESTRUTURA TABELA DE SERVIDORES PUBLICOS
CREATE TABLE IF NOT EXISTS api_aniversario_servidores (

id SERIAL PRIMARY KEY,
email VARCHAR(150) NOT NULL UNIQUE,
birth_date TIMESTAMP NOT NULL,
created_at TIMESTAMP NOT NULL
active BOOLEAN NOT NULL
);

